Первая версия ТЗ10
rossanatotolo/java-filmorate pull request #2
Opened 2024-07-13 09:13 UTC by rossanatotolo

2024-07-14 14:56 UTC, Fleaman777 requested changes

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    LocalDate minRealiseData = LocalDate.of(1895, 12, 28);
полу должно быть private, если только не требуется обратного

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private long getIdNext() { //Он находит max идентификатор среди уже добавленных публикаций и увеличивает его на единицу.
private методы должны идти после публичных, так при беглом просмотре класса, можно будет быстро понять, какой функционал он отдает наружу

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Отправлен ответ Put /films с телом {}", film);
много логов тоже не всегда хорошо, ухудшают восприятие самого кода

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription() != null && film.getDescription().length() > 200) {
проверку на длину так же можно бы сделать через аннотации

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription() != null && film.getDescription().length() > 200) {
200 можно было бы вынести в константу, что бы было удобно управлять значением и всегда видно было, за что именно оно отвечает

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Недопустимая дата релиза");
можно даже немного повысить уровень логирования, например до warn

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Long id;
поля должны быть private

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    LocalDate releaseDate; // дата релиза
на это поле тоже можено было бы повесить валидацонную аннотацию

2024-07-14 14:56 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String email;
на email поле тоже можено было бы повесить валидацонную аннотацию  @Email

2024-07-14 14:56 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +}
отличные тесты, настоящие интеграционные!

2024-07-14 14:56 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +}
общую часть в тест методах(подготовку тестового объекта фильм) можно вынести в общие методы, что бы уменьшить дублирование

2024-07-14 14:56 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
аналагично с тестами для FilmController

2024-07-14 15:49 UTC, rossanatotolo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Отправлен ответ Put /films с телом {}", film);
а я чет даже не знаю, какие можно убрать. Они у меня на поступление запроса и отправка ответа, плюс обработка в случае ошибок))

2024-07-14 15:57 UTC, rossanatotolo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription() != null && film.getDescription().length() > 200) {
я указала через такую аннотацию @Size(max = 200, message = "Максимальная длина описания - 200 символов"), в этом случае константа наверное уже не нужна? ведь можно сразу задать значение в аннотации поля

2024-07-15 05:24 UTC, rossanatotolo commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +}
Я так и не поняла, как это сделать(

2024-07-15 05:27 UTC, rossanatotolo commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
и тут также, в пачке написала по этому вопросу

2024-07-15 14:08 UTC, Fleaman777 approved these changes

2024-07-15 14:08 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @DateReleaseValidation
🔥

2024-07-15 14:08 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
отвечу в пачке)

2024-07-18 10:01 UTC, merged